### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by EvanHerman** [nekojira/wp-api-menus#10]
I have this installed alongside v 2 of the WordPress REST API.

When I try and hit '/wp-json/wp/v2/menus/' I'm getting a 404 error:
```
{
  "code": "rest_no_route",
  "message": "No route was found matching the URL and request method",
  "data": {
    "status": 404
  }
}
```
Any ideas?

Evan

**Comment by EvanHerman** [comment]
Tested with version 1.2 of the API and things work. This no longer works with the latest release, but only with the legacy versions of the API.

http://v2.wp-api.org/
https://wordpress.org/plugins/rest-api/

Although they are still in beta, v1 is considered a legacy version at this point.


Evan

**Comment by nekojira** [comment]
perhaps we need to add api version in the route? http://v2.wp-api.org/extending/adding/

**Comment by EvanHerman** [comment]
I was able to get things setup up using the documentation for extending v2, but some things have changed and will break backwards compatibility with versions prior to v2.

Would you be interested in a pull request?

**Comment by EvanHerman** [comment]
Me here again. I've got things working as they were in version 1.2, but again things are not backwards compatible. If its something you'd like a PR for, feel free to let me know.

Evan

**Comment by nekojira** [comment]
Hey thanks for sorting this out

I think there should be a way to check for API version and according to that, change the plugin behaviour - for the time being I'd like to maintain v1 compatibility because it's what most people who have this plugin are using. But if it's really not possible to have and API version check, then maybe we can make another branch v2 and merge the changes when v2 is out of beta and official?

**Comment by EvanHerman** [comment]
@nekojira That makes sense and I do agree. Breaking backwards compatibility is never a good thing.  I am going to work on a PR that merges the two based on which version of the WP API the user is running.

I should have a PR before the end of the day.

**Comment by nekojira** [comment]
I received a PR today with additions that should handle both v1 and v2 API

please have a look too, I should push these changes over wordpress.org as well and issue a new release

**Comment by EvanHerman** [comment]
Hi nekojira,

Sorry I never got back to you on this. I have been super busy with getting a few other plugins launched.

I'm glad you received an alternate PR. Hopefully that works out!


Best,
Evan

**Comment by nekojira** [comment]
cool, what you've been working at?

**Comment by EvanHerman** [comment]
I've been working on a very large re-write of our MailChimp plugin. We had released it, but as I'm sure you know - small things popped up here and there so I've been playing damage control until things smooth out while people transition over to the new version.
