### ISSUE TITLE
Menu Locations: Hyphenated is broken

### ISSUE THREAD

**Issue by subsumo** [nekojira/wp-api-menus#8]
I have a main-menu location and it's not pulling (no route matched). Leads me to believe the hyphen is causing a problem in the URL.

**Comment by tdlm** [comment]
I second this.

(?P<location>\w+) doesn't match hyphenated locations.

Check the regex match here (not working): https://regex101.com/r/qK3bP8/1

However, if we update the regex to (?P<location>[a-zA-Z0-9_-]+) it works:

https://regex101.com/r/hG6tS5/1
